### ISSUE TITLE
Add automatic submission page refresh

### ISSUE THREAD

**Issue by etiaro** [sio2project/oioioi#104]
It would be nice if the submissions list/submission page would automatically refresh when the submission status changes.

**Comment by tudny** [comment]
FYI: https://jira.sio2project.mimuw.edu.pl/browse/SIO-2455

**Comment by Michcioperz** [comment]
> I think an extra bonus would be to entertain the user with live information about his/her submission like: Running test 1/5/11/24/... like on codeforces, themis or solve

Doesn't this severely breach our existing separation of concerns between oioioi and sioworkers? Also good to remember that we must never send more information to user than they are permitted to see, for example accidentally revealing the score in a contest where the scores are still hidden

**Comment by DietPawel** [comment]
It does if You consider the most straightforward implementation, still I found this feature entertaining on other systems (when I was using them) and posted this idea more as a wish not as a proper suggestion.

**Comment by top-sekret** [comment]
> I think an extra bonus would be to entertain the user with live information about his/her submission like: Running test 1/5/11/24/... like on codeforces, themis or solve

I also think that we could introduce a smart judge system (run tests asynchronously as it does but stop running a subtask immediately if a test fails), which would reduce load, but would also conflict with such information.

Also, I think some contestants would try to get creative and push cheesy, incorrect solutions by somehow observing the test case numbers.
