### ISSUE TITLE
Update versions of checkout & python-setup in OIOIOI Github actions

### ISSUE THREAD

**Issue by twalen** [sio2project/oioioi#133]
The `actions/checkout@v2`, `actions/setup-python@v2` are deprecated and should be updated to:
- `actions/checkout@v3`
- `actions/setup-python@v4`

Related warning message in builds:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2

**Comment by sommbre** [comment]
Closing manually as PR didn't auto-close this issue
