### ISSUE TITLE
Create szkopul_settings in repository

### ISSUE THREAD

**Issue by etiaro** [sio2project/oioioi#162]
Simplify settings file on szkopul by moving as much as possible into of settings.py into oioioi/szkopul_settings.py in this repository

**Comment by LiquidPL** [comment]
I'm not sure how szkopuł is deployed, but either way I don't think that storing deployment-specific settings in a main project repo is a good idea. It'll only lead to confusion as people trying to deploy OIOIOI might think `szkopul_settings.py` is necessary for something.

If anything I'd rather refactor the whole settings to make it easier to adjust settings without having to edit Python files, for instance - through env vars (which would make Docker container configuration easier as well).
