### ISSUE TITLE
Rounds in "Tasks" tab should have start and end date

### ISSUE THREAD

**Issue by craniac-swistak** [sio2project/oioioi#175]
Currently rounds have only end date, e.g. on https://sio2.mimuw.edu.pl/c/oi30-3/p/
I suggest that they also have the start date. Say, Dzień drugi (22 Marzec 2023, 09:00 - 22 Marzec 2023, 14:00). This will be an additional check to avoid leaking tasks.

**Comment by twalen** [comment]
fixed
