### ISSUE TITLE
Wrong links in modules documentation

### ISSUE THREAD

**Issue by twalen** [sio2project/oioioi#201]
Some links in the docs are outdated:

* it is: http://icpc.baylor.edu/
* it should be: https://icpc.global/ or https://en.wikipedia.org/wiki/International_Collegiate_Programming_Contest

* it is: http://amppz.mimuw.edu.pl/
* it should be: https://pl.wikipedia.org/wiki/Akademickie_Mistrzostwa_Polski_w_Programowaniu_Zespo%C5%82owym

**Comment by DietPawel** [comment]
I would argue the wikipedia article would be helpful at all.

I suggest:
- in `oioioi.acm` http://icpc.baylor.edu/
- in `oioioi.amppz` link to https://amppz.edu.pl and also other hosts webpages: http://amppz.tcs.uj.edu.pl/ and http://amppz.ii.uni.wroc.pl/

**Comment by DietPawel** [comment]
I removed to link to #286 as currently it does not *fully* close this issue

**Comment by MasloMaslane** [comment]
http://icpc.baylor.edu/ doesn't work, I think it should be https://icpc.global/

**Comment by DietPawel** [comment]
> http://icpc.baylor.edu/ doesn't work, I think it should be https://icpc.global/

Yeah, I pasted the wrong one. Thanks!
