### ISSUE TITLE
'Add user to contest' form doesn't have an option for direct add

### ISSUE THREAD

**Issue by Aszanat** [sio2project/oioioi#220]
As @A-dead-pixel said in Issue #206 comment, adding a (autocomplete) search field would be very appreciated in 'Add user to contest' form, because there is no way to directly add a single person now - it's possible only by sending them an invitation link or by adding all users from a different contest. I suggest adding a button and a new url like 'Add Teacher' (in Teachers) or 'Add contest permission' (in Contest Permissions) OR adding just that search field with the option to add the person found to the contest.

**Comment by twalen** [comment]
https://github.com/sio2project/oioioi/pull/307

**Comment by twalen** [comment]
I've added minor comments to PR
