### ISSUE TITLE
Upgrade sandboxes

### ISSUE THREAD

**Issue by LiquidPL** [sio2project/oioioi#23]
Would it be possible to bring the versions of sandboxes up to the newest versions? Especially `vcpu_exec`, as the currently used version of Pin refuses to launch on newer versions of Linux.

**Comment by michcioperz** [comment]
We are in process of replacing oitimetool with [sio2jail](https://github.com/sio2project/sio2jail), which replaces Pin with seccomp. ~~By "in process of" I mean "on production (and it's working)".~~

**Comment by DietPawel** [comment]
Currently we use sio2jail in development and production. Relevant sandboxes run on modern Linux version. I am going to close this issue, but feel free to reopen it if necessary.
