### ISSUE TITLE
The gcc 10.2.1 sandbox isn't gzipped despite the .gz extension

### ISSUE THREAD

**Issue by A-dead-pixel** [sio2project/oioioi#234]
It is available at https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-gcc.10_2_1.tar.gz, but despite the .gz suffix it isn't compressed.
One can check this by running ``file`` or ``gzip -d`` on it.
I don't know whether this was intentional, but nevertheless it noticeably slows down docker builds.

**Comment by DietPawel** [comment]
You are right. I think there was some boxes redesign, which made sb forget the -z argument to tar. I am not sure about the source of this bug, but I identified uncompressed files
```
compiler-gcc.10_2_1.tar.gz: POSIX tar archive (GNU)
compiler-gcc.12_2_0.tar.gz: POSIX tar archive (GNU)
compiler-python3.11.2-numpy_amd64.tar.gz: POSIX tar archive (GNU)
compiler-python3.9.2-numpy_amd64.tar.gz: POSIX tar archive (GNU)
null-sandbox.tar.gz: POSIX tar archive (GNU)
```

**Comment by DietPawel** [comment]
I gziped the files, hope it helped.
