### ISSUE TITLE
Not a simple installation, vagrant up

### ISSUE THREAD

**Issue by Hacper** [sio2project/oioioi#25]
Hello,
I wanted to install SIO2 through simple installation. I installed vagrant and fired: vagrant up. Effect:
[LINK](https://pastebin.com/AvXMkAaH)
As you can see it does not work. What to do?
Regards.
Sorry for my English.

**Comment by SzymonPajzert** [comment]
Hi,

We recently tried to move from vagrant to docker installations. Are you able to create instance of that? Which version of vagrant do you use?

Best,
Szymon

**Comment by Hacper** [comment]
I will try a docker installation. Thank you.
Regards

**Comment by cytadela8** [comment]
Vagrant installations were fixed this year. We have a CI monitoring now so they are working and shouldn't stop working.
Docker images are being fixed right now. See https://gerrit.sio2project.mimuw.edu.pl/#/c/3118/
