### ISSUE TITLE
Error in the docker installation

### ISSUE THREAD

**Issue by Hacper** [sio2project/oioioi#26]
Hello,
during the OIOIOI installation using the docker, in the command:

> docker build -t oioioi .

during step 32 I received an error:

> Step 32/32 : RUN ./manage.py download_sandboxes -q -y -c /sio2/sandboxes
>  ---> Running in 229620a57ae6
> Traceback (most recent call last):
>   File "./manage.py", line 14, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
>     django.setup()
>   File "/home/oioioi/.local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/oioioi/.local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
>     "duplicates: %s" % app_config.label)
> django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: workers
> The command '/bin/sh -c ./manage.py download_sandboxes -q -y -c /sio2/sandboxes' returned a non-zero code: 1

What to do?
Regards.
Sorry for my English.

**Comment by cytadela8** [comment]
This issue no longer happens. Docker installation should work now.
