### ISSUE TITLE
(Docker) installation problem

### ISSUE THREAD

**Issue by jstpp** [sio2project/oioioi#261]
Hey!
I noticed that there are some problems with installation using docker.

![Screenshot_20230915_071731_Termius](https://github.com/sio2project/oioioi/assets/97021244/141fca92-0421-4a56-a406-fe40032c373c)

It looks like we don't have access to one of the files. Is it normal? If it does, I would be grateful for some help with handling this problem...

**Comment by A-dead-pixel** [comment]
This isn't intended behaviour, it seems that the permissions on the recently uploaded `sio2jail_exec-sandbox-1.4.4` are somehow wrong.
I'm guessing that @MasloMaslane should be pinged.

The simplest temporary workaround would be commenting out the last step in the Dockerfile, as workers are capable of downloading sandboxes on their own.

**Comment by MasloMaslane** [comment]
Sorry, this should now be fixed

**Comment by jstpp** [comment]
Thanks for help! Everything is OK now.
