### ISSUE TITLE
"Submission judged" notifications leak score

### ISSUE THREAD

**Issue by A-dead-pixel** [sio2project/oioioi#263]
Steps to reproduce:
1. Setup the notifications server
2. Set the timezone to 'Europe/Warsaw'
3. Have a simple contest
4. Make a round with the "Results date" set to 1 (or below 2 ?) hours after the current time
5. Submit to that round from a normal user account
6. See either in the desktop notification (you have to agree to those) or in the developer console that the score has been leaked

**Comment by DietPawel** [comment]
I can confirm this. And to my knowledge this is the only reason notification were disabled on sio2.
