### ISSUE TITLE
Registration message looks wrong on sio2.mimuw

### ISSUE THREAD

**Issue by A-dead-pixel** [sio2project/oioioi#266]
I don't know whether this has been noticed yet, but on sio2.mimuw the registration message isn't in a colored box like it should.

Screenshots:

sio2.mimuw.edu.pl:
![image](https://github.com/sio2project/oioioi/assets/82606748/ec66fbbf-e358-4364-979d-fc5d8b93e7c8)

SZKOpuł:
![image](https://github.com/sio2project/oioioi/assets/82606748/89513784-208c-4de5-af70-c61a98df51d1)

**Comment by MasloMaslane** [comment]
Thanks for noticing! I fixed it.
