### ISSUE TITLE
Add support for displaing extra text on contest pages

### ISSUE THREAD

**Issue by DietPawel** [sio2project/oioioi#281]
I propose to add support for custom HTML displayed on contest pages like:
- Questions and news
- New question
- Submissions
- New submission
- Test Run
- Files
- Forum
- Ranking

It should be modifiable in contest controller (or/and) in the web UI.

This way we can flexibly address concerns like #279

**Comment by twalen** [comment]
https://github.com/sio2project/oioioi/pull/284
