### ISSUE TITLE
Add a dark theme

### ISSUE THREAD

**Issue by patgra1410** [sio2project/oioioi#285]
I propose to add a dark theme to SIO, I don't think there is much more to add. Many people complete OI problems at night and would much rather not get their eyes burnt out.

**Comment by Antix7** [comment]
Rel

**Comment by MasloMaslane** [comment]
Adding dark theme isn’t currently a priority, here are the reasons: #106. Personally, I’m using [this](https://github.com/darkreader/darkreader) extension for dark theme and it works quite well on SIO
