### ISSUE TITLE
Interactive problems via IO

### ISSUE THREAD

**Issue by DietPawel** [sio2project/oioioi#287]
We have a request to support interactive problems via stdio + flush rather than with a library on Szkopuł.

Consider [this](https://codeforces.com/problemset/problem/1776/C) as an example

**Comment by MasloMaslane** [comment]
Interactive tasks with IO described by Krzysztof Małysa in his master thesis in point 4.14.1: https://github.com/varqox/masters_thesis/blob/main/main.pdf

Source code for interactive tasks with IO: https://github.com/varqox/sim-project/blob/main/subprojects/simlib/src/sim/judge/test_on_interactive_test.cc

Unit tests: https://github.com/varqox/sim-project/blob/main/subprojects/simlib/test/sim/judge/test_on_interactive_test.cc

**Comment by DietPawel** [comment]
I think we can get away without introducing third process to forward the communication as described in the 4.14.1 by utilizing `WTERMSIG` on status from `waitpid(2)`. If the user process returns due to SIGPIPE we can ignore it if checker gave us the answer or treat it as SE when checker did not gave the verdict.

**Comment by geoff128** [comment]
https://docs.google.com/document/d/1UEEOPyCRUpJRQv_nfrapkYvn31wIE604Z6beHlZPiW8/edit?usp=sharing
