### ISSUE TITLE
in PA controller, providing an address during the registration should be optional 

### ISSUE THREAD

**Issue by Kostero** [sio2project/oioioi#293]
This is just for sending prizes. If someone lives overseas or does not want the prize, they should not need to provide any fake addresses.

**Comment by twalen** [comment]
best case scenario: provide checkbox button "I don't wan't to give my address" that makes address fields not required.

**Comment by zggf-zggf** [comment]
I assume T-shirt size should also be optional.

**Comment by Kostero** [comment]
An even better solution: if we could have a seperate form and ask people only after the won prizes, that would be great.

**Comment by twalen** [comment]
PR: #298
