### ISSUE TITLE
Docker deployment failing with "oioioi-create-config: command not found"

### ISSUE THREAD

**Issue by mrapacz** [sio2project/oioioi#30]
Tried following the docker deployment installation, unfortunately it doesn't wanna bring the containers up and fails. 

Tried running the command on a clean instance of Ubuntu 14.04.
```
~# docker --version
Docker version 18.06.0-ce, build 0ffa825
~# docker-compose --version
docker-compose version 1.22.0, build f46880fe
```

See attached outputs of both `docker build` and `docker-compose` commands:
[docker build output](https://github.com/sio2project/oioioi/files/2260011/build_output.txt)
[docker-compose output](https://github.com/sio2project/oioioi/files/2260012/composeup_output.txt)

**Comment by Taikelenn** [comment]
In line 43 of Dockerfile, that is:
`RUN oioioi-create-config /sio2/deployment`
you can specify full path to the binary; if no changes to Dockerfile were made, then changing that line to
`RUN /home/oioioi/.local/bin/oioioi-create-config /sio2/deployment`
should fix the issue.

**Comment by cytadela8** [comment]
This was fixed and docker deployment works now.
