### ISSUE TITLE
Can't add new tags in admin problem settings

### ISSUE THREAD

**Issue by SZonkil** [sio2project/oioioi#304]
When adding a new tag to a problem, this error appears:
'<tag_name>' instance needs to have a primary key value before this relationship can be used.

**Comment by zggf-zggf** [comment]
It seems like related to [this issue](https://code.djangoproject.com/ticket/34084)
"Previously an empty queryset was implicitly returned for unsaved instances now you need to protect your code and check `self.instance.pk"`
