### ISSUE TITLE
"Edit submit/submissions message" buttons are visible to regular users

### ISSUE THREAD

**Issue by A-dead-pixel** [sio2project/oioioi#325]
The buttons for editing messages visible on the "submit" and "my submissions" pages, which were introduced in #284 are visible to regular users.
`oioioi/contests/templates/contests/my_submissions.html` seems to be at fault.

**Comment by DietPawel** [comment]
@MasloMaslane

**Comment by MasloMaslane** [comment]
Thanks for noticing, I'll fix it tomorrow
