### ISSUE TITLE
[Forum] Add a badge for posts of the contest admins

### ISSUE THREAD

**Issue by Kostero** [sio2project/oioioi#347]
It should be clearly visible in the forum when someone is an admin of the contest. 

Current footer of a post on forum by an admin:
12345 |  +46  -2 | Name of the admin | Added: 2024-XX-YY

Expected footer:
12345 |  +46  -2 | Name of the admin **(admin)** | Added: 2024-XX-YY

**Comment by DietPawel** [comment]
How about `moderator` in the context of ,,forum lingo''?

**Comment by Kostero** [comment]
Moderator is fine.
