### ISSUE TITLE
[Export Submissions] Allow contest admins to export submissions that were used for the final scoring

### ISSUE THREAD

**Issue by Kostero** [sio2project/oioioi#349]
Currently the only options are to export either all the submissions, or the last submissions (per user + task).

In some contests, the best submission counts (e.g. OIJ), so we would like to be able to download these submissions.

**Comment by dawidratynski** [comment]
It seems that the current functionality works exactly as described - in contests where the best submission is used for the final score, the best submission for each user is exported. The phrasing used in the menu is misleading and will likely need to be changed.

Related merge request:  #376
