### ISSUE TITLE
Round dates & times shown on tasks page are invalid.

### ISSUE THREAD

**Issue by twalen** [sio2project/oioioi#383]
It looks like PR #375 introduced an error in presenting start/end round date on the task page, i.e.

https://szkopul.edu.pl/c/laboratorium-z-asd-2023/p/

<img width="820" alt="image" src="https://github.com/sio2project/oioioi/assets/7008315/bc05d347-fbc3-44d8-b236-04a66475e0b5">

it should be "17 lutego 23:59"

**Comment by MasloMaslane** [comment]
Completed in #384
