### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by i13k** [sio2project/oioioi#386]
On szkopul and sio2.mimuw.edu.pl, there is Python support available, while in this repo (and sioworkers), I can see no such support. Can it be introduced?

**Comment by MasloMaslane** [comment]
Duplicate of #272 and #52. You can try using patches from https://github.com/sio2project/sioworkers/issues/8, but we hope to soon merge sioworkers from sio2.mimuw.edu.pl to the main repository

**Comment by i13k** [comment]
> we hope to soon merge sioworkers from sio2.mimuw.edu.pl to the main repository
Can't you do it now? I'd like to use this system for a competition, but the lack of Python support is a major roadblock.

**Comment by i13k** [comment]
Closing issue. If anybody knows how to allow Python submitions, please do tell me.
