### ISSUE TITLE
Problem with adding problems and accesing problemset

### ISSUE THREAD

**Issue by nixenos** [sio2project/oioioi#40]
When I try to add new problem to problemset or any contest I encounter an error: 
```python
NoReverseMatch at /c/test/problems/add
Reverse for 'global_portal' with arguments '()' and keyword arguments '{'link_name': 'default', 'portal_path': 'problemset'}' not found. 0 pattern(s) tried: []
```
Same for trying to access problemset. I use manual installation since I cannot use docker or vagrant image.

**Comment by michcioperz** [comment]
There's an upcoming change that we hope to merge today that removes task archive's dependency on the global portal https://gerrit.sio2project.mimuw.edu.pl/#/c/3235/

**Comment by nixenos** [comment]
That's great, can't wait to see this in mainline

**Comment by xvyx** [comment]
The change still needs some work and will not be merged today. For now you can enable oioioi.portals in settings.py to work around the issue.

**Comment by nixenos** [comment]
Ok, I can access problemset but when I try to add a test package I get following error:
```python
HTTP/500: [Errno 2] No such file or directory: 'touch' Traceback (most recent call last): File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/filetracker/servers/base.py", line 43, in __call__ return handler(environ, start_response) File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/filetracker/servers/files.py", line 77, in handle_PUT logical_size=logical_size) File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/filetracker/servers/storage.py", line 217, in store lutime(link_path, version) File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/filetracker/servers/storage.py", line 485, in lutime if subprocess.call(['touch', '-c', '-h', '-d', t, path]) != 0: File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/gevent/subprocess.py", line 240, in call with Popen(*popenargs, **kwargs) as p: File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/gevent/subprocess.py", line 635, in __init__ reraise(*exc_info) File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/gevent/subprocess.py", line 604, in __init__ restore_signals, start_new_session) File "/home/nixen/sio2/venv/local/lib/python2.7/site-packages/gevent/subprocess.py", line 1429, in _execute_child raise child_exception OSError: [Errno 2] No such file or directory: 'touch'
```
I'm running with venv activated.

**Comment by michcioperz** [comment]
I find your environment questionable. What operating system/distribution are you running?

**Comment by nixenos** [comment]
It's ubuntu 16.04 (VPS) with all updates done.

**Comment by michcioperz** [comment]
If you'd like to get help troubleshooting this, I'd suggest switching to a more immediate form of communication such as IRC: http://webchat.freenode.net/?channels=%23sio2project

**Comment by Wolf480pl** [comment]
Anyway, what is the result of running the following commands inside *and* outside of your venv?
- `echo $PATH`
- `which touch`
- `touch test.txt`

(It'd still be more convenient if you could hop on IRC, then we could troubleshoot more interactively)
