### ISSUE TITLE
Django issue

### ISSUE THREAD

**Issue by mich930** [sio2project/oioioi#41]
New django-formtools version came out few days ago which requires 1.11 Django, but installing Django 1.11 causes "oioioi 0.1.1.dev0 has requirement Django <1.11,>=1.10 but you'll have Django 1.11 which is incompatible" error

**Comment by michcioperz** [comment]
Django 1.11 is on our todolist, but it's a difficult one.

Is oioioi even depending on formtools though?

**Comment by mich930** [comment]
I don't know, I just installed previous version of it. By the way, how can
I easy change settings.py when using a virtual machine?

**Comment by Wolf480pl** [comment]
Can you try adding `django-formtools<=2.1` to requirements.txt as a workaround? It worked for me, or at least made pip install succeed. Haven't tested if the app runs fine with it.

**Comment by mich930** [comment]
I will try tomorrow.
