### ISSUE TITLE
Night build fails

### ISSUE THREAD

**Issue by twalen** [sio2project/oioioi#416]
Due to flaky test 
`oioioi/sinolpack/tests.py::TestSinolPackage::test_sigpipe_interactor_package_safe`
some of the night builds fail (looks like 20% chance of an error)

error message from failed build:
```
FAILED oioioi/sinolpack/tests.py::TestSinolPackage::test_sigpipe_interactor_package_safe 
- AssertionError: '' != 'solution exited prematurely'
```

**Comment by MasloMaslane** [comment]
This (hopefully) will be fixed when I add tests to https://github.com/sio2project/oioioi/pull/396

**Comment by twalen** [comment]
This is training ticket for TAG class :) We will resolve it in 30min.
