### ISSUE TITLE
Update Python version in Dockerfile & Github actions

### ISSUE THREAD

**Issue by twalen** [sio2project/oioioi#418]
Currently Python 3.8 is used for both Docker & Github actions (like pytest, nightbuild, cypress).

Python 3.8 is unsupported right now (end of life on 07 Oct 2024 - https://endoflife.date/python)

Consider updating to 3.9 or newer.
Please make sure that new version is compatible with current python dependencies (or update them)

**Comment by MasloMaslane** [comment]
This shouldn't be hard, as both sio2.mimuw and Szkopuł are running on Python 3.9.2
