### ISSUE TITLE
Space not allowed in last name field

### ISSUE THREAD

**Issue by mimi89999** [sio2project/oioioi#43]
Hello,
My first name is `Michel` and my last name is `Le Bihan`. When I submit the name form, I get the error `This value may contain only letters, numbers and punctuation marks.`.
I saw: https://github.com/sio2project/oioioi/blob/741edfaca882b6cab61b41c90e9eeaa7793e97e6/oioioi/base/utils/user.py#L6-L12
It seems really strange to me that some punctuation marks are allowed, but spaces aren't.

**Comment by mimi89999** [comment]
I also noticed that the message informing users about invalid characters in their name is displayed twice.
![Capture d’écran du 2020-04-09 17-30-21](https://user-images.githubusercontent.com/8530546/78914846-51d24900-7a8b-11ea-8256-15964869bd41.png)
![Capture d’écran du 2020-04-09 17-48-49](https://user-images.githubusercontent.com/8530546/78914849-526adf80-7a8b-11ea-83ea-b4fb7d88b4b9.png)

**Comment by accek** [comment]
Hi,

thanks for the report. :)

This wasn't intentional and it's now fixed in the code.
Expect a few weeks until the fix is deployed on szkopul.edu.pl.
