### ISSUE TITLE
Wiki misguidance

### ISSUE THREAD

**Issue by matihope** [sio2project/oioioi#74]
It says, 
```yml
points:
    1: 30
    2: 70
```
in both polish and english version of the wiki, while writing "points" in config.yml does nothing to the package, but switching it to
```yml
scores:
    1: 30
    2: 70
```
does indeed give desired results.
Here is a link to the article: https://github.com/sio2project/oioioi/wiki/%5BEN%5D-2.-Configuration-file

**Comment by LightFelicis** [comment]
You are right, we had a mistake in the example :-) Thankfully, in the detailed description we had `scores`. 
I fixed the wiki.
