### ISSUE TITLE
Network error when downloading files with size >1G

### ISSUE THREAD

**Issue by HeRaNO** [sio2project/oioioi#89]
When I'm downloading [test cases to `Skrzyżowania`](https://sio2.mimuw.edu.pl/c/pa-2021-1/tests/386/), it always responds `Network error` when 1G of the file downloaded. Maybe `proxy-max-temp-file-size` should be set to a bigger value in [NGINX config](https://github.com/sio2project/oioioi/blob/master/oioioi/deployment/nginx-site.conf.template).

**Comment by Michcioperz** [comment]
I can reproduce this (it actually got about 200K beyond the 1G border for me) but I don't have production access to fix it

**Comment by HeRaNO** [comment]
> I can reproduce this (it actually got about 200K beyond the 1G border for me) but I don't have production access to fix it

Thanks for reproducing. Would others take a look at it?

**Comment by HeRaNO** [comment]
> > I can reproduce this (it actually got about 200K beyond the 1G border for me) but I don't have production access to fix it
> 
> Thanks for reproducing. Would others take a look at it?

Now it can be downloaded.
